### ISSUE TITLE
[S2 - PBI3] Rangkuman Data Penjualan & Proses Transaksi Berjalan

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#10]
Admin dapat melihat rangkuman data penjualan yang telah selesai dan proses transaksi yang sedang dilakukan

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270026-8b00a7ba-88fc-4a53-b73d-f6ce826b194d.png)

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270035-34d51b1e-7880-4e62-8e01-5e9e067736ce.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1af4fb8a-7fff-aa92-c5f6-435ae122682b"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | A-01
-- | --
Nama Use-Case | Mengelola Dashboard Transaksi Penjualan, Melihat Halaman List Transaksi
Aktor | Admin
Deskripsi | Admin dapat melihat rangkuman data penjualan yang telah selesai dan proses transaksi yang sedang dilakukan
Normal Course | 1.Admin melihat rangkuman data penjualan
Alternate Course | -
Pre Condition | Admin ingin mengetahui performa penjualan perusahaan
Post Condition | Admin berhasil mengetahui performa penjualan perusahaan

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270995-16c9eb2a-e2d3-4779-adab-66ab9fa7354c.png)

**Comment by kanzaazzahra** [comment]
https://user-images.githubusercontent.com/92237624/170802755-089ccad8-ef64-414e-aba4-395c5df25339.mp4
