### ISSUE TITLE
[S2 - PBI4] CRUD Detail Data Penjualan & Proses Transaksi Berjalan

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#11]
Admin dapat melihat,merubah,membuat dan menghapus secara detail data penjualan yang telah selesai dan proses transaksi yang sedang dilakukan

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270065-b112422c-efd8-42ca-8396-31ec50cf110c.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-a3080b27-7fff-15db-b1b5-4f13d70aae46"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | A-02
-- | --
Nama Use-Case | Manajemen Pembeli
Aktor | Admin
Deskripsi | Admin dapat melihat,merubah, dan menghapus secara detail data penjualan yang telah selesai dan proses transaksi yang sedang dilakukan
Normal Course | 1.Admin membuka detail transaksi tertentu2.Admin dapat melihat,merubah, dan menghapus detail transaksi tertentu
Alternate Course | -
Pre Condition | Admin ingin melihat,merubah, dan menghapus secara detail data penjualan
Post Condition | Admin berhasil melihat,merubah, dan menghapus secara detail data penjualan

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270917-0600a58b-826e-4a42-8e4b-bb647cd765db.png)

**Comment by ekkynovrizalam** [comment]
Di tambahkan field upload photo evidence (optional)

**Comment by fdwulan** [comment]
Halo Pak, saya izin untuk mengumpulkan video demonstrasi dari PBI ini , terimakasih

https://user-images.githubusercontent.com/90902848/170662108-88492923-b13c-4b39-9f1d-ace8d71df1bb.mp4
