### ISSUE TITLE
[S2 - PBI5] Biodata Pribadi

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#12]
Pembeli dapat melihat, merubah biodata pribadi yang dimiliki

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269888-64a9ef43-61c3-4cb2-8be5-e62d230aee2b.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-3f1fa351-7fff-a2d9-b0d6-255545eea7f7"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-09
-- | --
Nama Use-Case | Melihat Halaman Profil
Aktor | Pembeli
Deskripsi | Pembeli dapat  melihat,merubah biodata pribadi yang dimiliki dalam halaman profile
Normal Course | 1.Pembeli membuka halaman profil2.Pembeli ingin merubah data tertentu
Alternate Course | -
Pre Condition | Pembeli ingin melakukan perubahan terhadap profil
Post Condition | Pembeli berhasil melakukan perubahan terhadap profil

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270968-0df50458-d7d5-4e68-bb33-59ec5197b6fc.png)

**Comment by cahyobrahim** [comment]
Selamat malam pak, saya izin untuk mengumpulkan video demonstrasi ya pak. Terima kasih pak

https://user-images.githubusercontent.com/54279892/170773398-f57675e0-770d-467a-8586-e024b1ddd469.mp4
