### ISSUE TITLE
[S3 - PBI1] CRUD Informasi Tahapan Pengajuan

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#13]
Admin dapat melihat,merubah,membuat dan menghapus informasi tahapan pengajuan oleh pembeli sehingga saya bisa melakukan update informasi

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270017-5046a350-2b3e-4169-af20-46aedfc0a53b.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9f1c29c2-7fff-9f19-49e7-e22c88a46c60"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | A-03
-- | --
Nama Use-Case | Mengelola Tahapan Layanan Pengajuan
Aktor | Admin
Deskripsi | Admin dapat melihat,merubah,membuat dan menghapus informasi pengajuan administrasi dari customer sehingga saya bisa melakukan update informasi
Normal Course | 1.Admin membuka  informasi pengajuan administrasi2.Admin dapat melihat,merubah, dan menghapus  informasi pengajuan administrasi
Alternate Course | -
Pre Condition | Admin ingin melihat,merubah,membuat dan menghapus informasi informasi pengajuan administrasi
Post Condition | Admin berhasil melihat,merubah,membuat dan menghapus informasi  informasi pengajuan administrasi

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160271095-23929de0-1730-486c-9816-7345b37fcfd4.png)

**Comment by cahyobrahim** [comment]
https://user-images.githubusercontent.com/54279892/174895250-60532a9e-8b36-484f-9e05-b11ec2e6b462.mp4
