### ISSUE TITLE
[S3 - PBI3] Gambaran Harga Rataan

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#16]
Pembeli dapat melihat gambaran harga rata-rata tanah dari masing-masing daerah

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269977-7272bf14-1a7b-4d1a-a797-7588d8d14799.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-19087086-7fff-bfb9-312e-8d7a85aa2496"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-08
-- | --
Nama Use-Case | Melihat Halaman Dashboard Tanah
Aktor | Pembeli
Deskripsi | Pembeli dapat  melihat gambaran harga rata-rata tanah dari masing-masing daerah.
Normal Course | 1.Pembeli membuka halaman dashboard rata-rata tanah2.Pembeli melihat harga rata-rata tanah dari daerah tertentu
Alternate Course | -
Pre Condition | Pembeli ingin melihat gambaran harga rata-rata tanah dari daerah tertentu
Post Condition | Pembeli mengetahui gambaran harga rata-rata tanah dari daerah tertentu

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160271140-7f3bfff6-3e52-4771-9ff6-f28ac5ce7c52.png)

**Comment by kanzaazzahra** [comment]
https://user-images.githubusercontent.com/92237624/174656273-8899599d-9e73-4781-a533-ecf7390a9853.mp4
