### ISSUE TITLE
[S3 - PBI5] CRUD Informasi Rataan Harga Tanah

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#17]
Admin dapat melihat, merubah, membuat, dan menghapus informasi rata-rata harga tanah yang berada pada daerah yang diincar

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269948-07ccf6a0-ce21-4309-bd1d-63ccd5818173.png)

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270413-32aa1f3e-da9f-4443-8c0d-424366d52009.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-aaa1a5b3-7fff-c30c-878a-5365c1e843e2"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | A-05
-- | --
Nama Use-Case | Mengelola Dashboard Tanah
Aktor | Admin
Deskripsi | Admin dapat melihat, merubah, membuat, dan menghapus informasi rata-rata harga tanah yang berada pada daerah yang diincar
Normal Course | 1.Admin memasukan link dashboard tanah
Alternate Course | -
Pre Condition | Admin ingin melihat, merubah, membuat, dan menghapus informasi rata-rata harga tanah
Post Condition | Admin berhasil melihat, merubah, membuat, dan menghapus informasi rata-rata harga tanah

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160271116-397c17af-5a97-43b9-820d-eccd182cbd98.png)

**Comment by fdwulan** [comment]
https://user-images.githubusercontent.com/90902848/174936591-23d494f8-de96-4f1b-9e50-e04b7582cce3.mp4
