### ISSUE TITLE
[S1 - PBI3] Pengajuan Jual Tanah

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#3]
Pembeli dapat melakukan pengajuan jual tanah

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269814-e0b3d397-45b3-4970-a370-3587497bfc95.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-99b2d8a2-7fff-ac00-8962-ae2a1b1d6926"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-02
-- | --
Nama Use-Case | Melakukan Pengajuan Jual Tanah
Aktor | Pembeli
Deskripsi | Pembeli dapat melakukan pengajuan jual tanah
Normal Course | 1.Pembeli mengisi form data mengenai tanah yang akan dijual2.Pembeli melakukan upload sertifikat tanah3.Pembeli melakukan upload foto tanah
Alternate Course | -
Pre Condition | Pembeli ingin mengajukan pengajuan penjualan tanah
Post Condition | Pembeli berhasil mengajukan pengajuan penjualan tanah

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270641-4b4ecd5f-c326-4dba-9857-e52f9a2b755e.png)

**Comment by ekkynovrizalam** [comment]
PBI ini saya terima jika proses pengajuan ini bisa dikelola datanya oleh penjual. Bisa di CRUD. gmna?

**Comment by rebimantoro** [comment]
baik pak, bisa diusahakan
