### ISSUE TITLE
[S1 - PBI4] Pengajuan Sertifikat Tanah

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#4]
Pembeli dapat melakukan pengajuan sertifikat tanah untuk menjamin kepastian hukum dan perlindungan hukum yang berlaku

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269823-bcef5c30-97b7-4537-9522-bec5124c5967.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-b1a1668a-7fff-f5d8-c932-ab9b36b9197a"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-03
-- | --
Nama Use-Case | Membuat Sertifikat Tanah
Aktor | Pembeli
Deskripsi | Pembeli dapat membuat sertifikat tanah untuk menjamin kepastian hukum dan perlindungan hukum yang berlaku
Normal Course | 1.Pembeli mengisi form data mengenai tanah yang akan dijual2.Pembeli melakukan upload foto tanah
Alternate Course | -
Pre Condition | Pembeli ingin mengajukan membuat sertifikat tanah
Post Condition | Pembeli berhasil mengajukan pengajuan membuat sertifikat tanah

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270651-4dcbd7b2-d080-4523-a3f0-a590dcd6e5bc.png)

**Comment by ekkynovrizalam** [comment]
PBI ini saya terima jika proses pengajuan ini bisa dikelola datanya oleh pembeli. Bisa di CRUD. gmna?

**Comment by rebimantoro** [comment]
baik Pak, bisa diusahakan
