### ISSUE TITLE
[S1 - PBI5] Pengajuan Pergantian Pemilik Tanah

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#5]
Pembeli dapat melakukan pengajuan pergantian pemilik tanah apabila tanah tersebut sudah sah dibeli

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269843-ab7d65a1-b983-45a0-a175-2275cc008184.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-312dd619-7fff-2611-27b4-9a686bb6352e"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-04
-- | --
Nama Use-Case | Melakukan Pergantian Pemilik Tanah
Aktor | Pembeli
Deskripsi | Pembeli dapat melakukan pergantian pemilik tanah apabila tanah tersebut sudah sah dibeli
Normal Course | 1.Pembeli mengisi form data mengenai tanah yang akan dijual2.Pembeli melakukan upload foto tanah3.Pembeli melakukan upload sertifikat tanah
Alternate Course | -
Pre Condition | Pembeli ingin mengajukan Pergantian Pemilik Tanah
Post Condition | Pembeli berhasil mengajukan Pergantian Pemilik Tanah

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270656-12749d34-fe07-46ed-bc22-ad0820d0c163.png)

**Comment by ekkynovrizalam** [comment]
PBI ini saya terima jika proses pengajuan ini bisa dikelola datanya oleh pembeli. Bisa di CRUD. gmna?

**Comment by rebimantoro** [comment]
baik pak, bisa diusahakan

**Comment by ekkynovrizalam** [comment]
klo gtu di update dulu ya requirementnya. activity dan usecase descriptionnya. anda boleh membuat detail usecase description berbeda jika diperlukan. misalnya create, edit dan delete

**Comment by rebimantoro** [comment]
sebetulnya untuk read itu nanti di halaman riwayat yang akan dikerjakan di sprint selanjutnya Pak, tetapi saya bingung untuk proses Update, karena pengajuan tanah itu langsung masuk ke halaman admin , dari sisi probis yang melakukan posting produk itu admin Pak
