### ISSUE TITLE
[S3 - PBI4] Tentang Kami

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#6]
Pembeli dapat melihat halaman tentang kami agar saya bisa mengetahui informasi tentang aplikasi web Tanahin

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269849-dde369f7-e7eb-46a4-a748-111a827b676b.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-c81f5180-7fff-8ee7-ead0-3b64000f122c"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-10
-- | --
Nama Use-Case | Melihat Halaman Tentang Kami
Aktor | Pembeli
Deskripsi | Pembeli dapat melihat halaman tentang kami agar saya bisa mengetahui informasi tentang aplikasi web Tanahin
Normal Course | 1.Pembeli melihat halaman tentang kami
Alternate Course | -
Pre Condition | Pembeli ingin mengetahui informasi tentang  aplikasi web Tanahin
Post Condition | Pembeli berhasil mengetahui informasi mengenai web Tanahin

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270722-2b6e5723-11cc-4e4f-ba0b-2a0adddbad91.png)

**Comment by ekkynovrizalam** [comment]
PBI ini belum prioritas. jangan di kerjakan di sprint 1 ya.

**Comment by ekkynovrizalam** [comment]
Termasuk CRUD untuk update kontak dan konten tentang kami

**Comment by edbertsalim** [comment]
[https://youtu.be/ZSqNBaspd_s](url)
