### ISSUE TITLE
[S3 - PBI2] Prosedur Penggunaan

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#7]
Pembeli dapat melihat halaman prosedur untuk memahami bagaimana cara penggunaan aplikasi

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269875-ec4b41e4-525c-40c0-a5f2-7f7087d5c6d8.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-233f7908-7fff-91c0-f19b-c73b689495df"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-11
-- | --
Nama Use-Case | Melihat Halaman Prosedur
Aktor | Pembeli
Deskripsi | Pembeli dapat melihat halaman prosedur untuk memahami bagaimana cara penggunaan aplikasi
Normal Course | 1.Pembeli melihat halaman prosedur
Alternate Course | -
Pre Condition | Pembeli ingin memahami bagaimana cara penggunaan aplikasi
Post Condition | Pembeli berhasil memahami bagaimana cara penggunaan aplikasi

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270752-41f05c2a-3e36-4ca7-9e31-214b9be735c5.png)

**Comment by ekkynovrizalam** [comment]
termasuk CRUD dari sisi admin

**Comment by rebimantoro** [comment]
https://user-images.githubusercontent.com/76649910/174841853-6a5b76d8-6bec-4736-971b-30ce65ff3dcd.mp4

Selamat Malam Pak, saya izin untuk mengirimkan demonstrasi fitur pada PBI ini, Terimakasih
