### ISSUE TITLE
[S2 - PBI1] Menambah Produk

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#8]
Admin dapat menambah produk sehingga web ini mempunyai banyak produk yang tersedia

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160269964-f16d25ec-2e1e-422a-af93-a41c0cc0d3d2.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-d94abc2f-7fff-6924-491a-56cc1ab19ce1"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | A-04
-- | --
Nama Use-Case | Menambah produk
Aktor | Admin
Deskripsi | Admin dapat menambah produk sehingga web ini mempunyai banyak produk yang tersedia
Normal Course | 1.Admin mengisi form produk2.Admin melakukan upload sertifikat3.Admin Melakukan upload foto
Alternate Course | -
Pre Condition | Admin ingin menambah produk sehingga web ini mempunyai banyak produk yang tersedia
Post Condition | Admin berhasil menambah produk sehingga web ini mempunyai banyak produk yang tersedia

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270787-4d96692c-fddc-4071-99d5-1e9a8bff5398.png)

**Comment by ekkynovrizalam** [comment]
ini sudah termasuk CRUD

**Comment by edbertsalim** [comment]
https://youtu.be/rvOut-h2WeI
