### ISSUE TITLE
[S2 - PBI2] Membeli Tanah

### ISSUE THREAD

**Issue by edbertsalim** [SI-RPL-2022/SI4302_A_TANAHIN#9]
Pembeli dapat membeli tanah dengan mudah melalui website Tanahin

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270109-ccbfe313-fd43-4c89-827f-3301192f0775.png)

**Comment by edbertsalim** [comment]
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-26890565-7fff-15c8-ef4a-25ef704f7685"><div dir="ltr" style="margin-left:0pt;" align="left">

Kode Use-Case | P-05
-- | --
Nama Use-Case | Membeli Tanah
Aktor | Pembeli
Deskripsi | Pembeli dapat membeli tanah dengan mudah melalui website Tanahin.
Normal Course | 1.Pembeli melihat-lihat tanah 2.Pembeli memilih tanah 3.Pembeli membeli tanah
Alternate Course | -
Pre Condition | Pembeli ingin mendapatkan tanah yang sesuai dengan keinginan
Post Condition | Pembeli berhasil membeli tanah

</div></b>
</body>
</html>

**Comment by edbertsalim** [comment]
![image](https://user-images.githubusercontent.com/92244740/160270818-0cf01d03-e5b9-4e70-be2a-ba4a63f7223c.png)

**Comment by rebimantoro** [comment]
![Market Place 3](https://user-images.githubusercontent.com/76649910/164577085-b25b2791-5089-4f75-8788-7c1fb81ee827.jpg)
![Market Place 2](https://user-images.githubusercontent.com/76649910/164577088-eeb9de19-7e8c-4268-a2c8-574f9362e7b4.jpg)

**Comment by rebimantoro** [comment]
Selamat pagi Pak, saya izin untuk mengumpulkan Demonstrasi PBI dari PBI ini ,Terimakasih

https://user-images.githubusercontent.com/76649910/170606852-56acbd08-0c33-40b2-b1d1-a400c307ac88.mp4
